version: '3.8'
services:
    web:
        build:
            context: ./docker/web/dev
        depends_on:
            - db
        env_file:
            - .env.local
        volumes:
            - ./:/var/www/html/
            - ~/.composer:/var/composer:cached
            - ./docker/web/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
            - ./docker/web/dev/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "80:80"
        networks:
            - default
            - external-network

    db:
        image: mariadb:10.3.31
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/db/init:/docker-entrypoint-initdb.d
        env_file:
            - .env.local
        ports:
            - "3306:3306"

volumes:
    db_data: { }

networks:
    external-network:
        external: true
    default: { }
